"""Parity between the Python registry and the TS registry dump.

registry.json is generated by `npm run gen:registry` (scripts/gen-registry-json.ts)
from the live TS functionRegistry. Any drift in the TS functions shows up here.
"""

import json
from pathlib import Path

import pytest

import pygeomatic as gm
from pygeomatic.functions.implementations.property_functions import (
    PROPERTY_ACCESSOR_KEYWORDS,
)

REGISTRY_JSON = Path(__file__).resolve().parents[1] / "registry.json"


@pytest.fixture(scope="module")
def ts_entries():
    return json.loads(REGISTRY_JSON.read_text())


def test_property_accessors_match(ts_entries):
    ts_props = {e["keyword"] for e in ts_entries if e["keyword"].startswith("_prop-")}
    assert ts_props == set(PROPERTY_ACCESSOR_KEYWORDS)


def test_keyword_sets_match(ts_entries):
    ts_kw = {e["keyword"] for e in ts_entries if not e["keyword"].startswith("_prop-")}
    # Macros live outside the TS functionRegistry dump (the editor registers
    # them at runtime from geometry.json), so exclude them here.
    py_kw = {kw for kw, f in gm.REGISTRY.items() if not f.is_macro}
    assert ts_kw == py_kw


def test_builtin_macros_match_public_json():
    """pygeomatic ships its own copy of the editor's auto-loaded macros; keep
    it byte-identical (modulo JSON formatting) to the web repo's file."""
    public = Path(__file__).resolve().parents[2] / "public/geomatic/macros/geometry.json"
    if not public.exists():
        pytest.skip("web repo's geometry.json not present (standalone checkout)")
    packaged = Path(__file__).resolve().parents[1] / "src/pygeomatic/macros.json"
    assert json.loads(packaged.read_text()) == json.loads(public.read_text())


def test_signatures_match(ts_entries):
    mismatches = []
    for e in ts_entries:
        if e["keyword"].startswith("_prop-"):
            continue
        f = gm.REGISTRY[e["keyword"]]
        py = {
            "name": f.name,
            "outputType": f.output_type,
            "isImperative": f.is_imperative,
            "isAsync": f.is_async,
            "category": f.category,
            "operandTypes": f.operand_types,
            "parameters": [
                {
                    "name": p.name,
                    "type": p.type,
                    "variadic": p.variadic,
                    "hasDefault": p.has_default,
                    "default": p.default if p.has_default else None,
                }
                for p in f.params
            ],
        }
        ts = {
            "name": e["name"],
            "outputType": e["outputType"],
            "isImperative": e["isImperative"],
            "isAsync": e["isAsync"],
            "category": e["category"],
            "operandTypes": e["operandTypes"],
            "parameters": e["parameters"],
        }
        if py != ts:
            mismatches.append((e["keyword"], py, ts))
    assert not mismatches, "\n".join(f"{kw}:\n  py: {py}\n  ts: {ts}" for kw, py, ts in mismatches)


def test_node_coercion_converts_cover_generated_table():
    """Every node-coercion pair probed from the live TS (coercions.json, via
    `npm run gen:registry`) must have a hand-mirrored convert in coercions.py —
    and no convert may outlive its TS counterpart. When type-coercion.ts gains
    a coercion, regenerate the json and this fails until the new convert is
    mirrored (see _NODE_CONVERTS)."""
    from pygeomatic.coercions import _NODE_CONVERTS, NODE_COERCIONS

    missing = NODE_COERCIONS - set(_NODE_CONVERTS)
    stale = set(_NODE_CONVERTS) - NODE_COERCIONS
    assert not missing, (
        f"type-coercion.ts has coercions with no python convert: {sorted(missing)} — "
        "mirror each convert in pygeomatic/coercions.py (_NODE_CONVERTS)"
    )
    assert not stale, (
        f"python converts no longer in type-coercion.ts: {sorted(stale)} — "
        "remove them from pygeomatic/coercions.py, or re-run `npm run gen:registry` "
        "if coercions.json is out of date"
    )


def test_node_property_whitelist_is_dsl_shaped():
    """Every whitelisted property is reachable as a python attribute and every
    exposed public attribute is whitelisted (or `id`)."""
    for node_type, props in gm.NODE_PROPERTIES.items():
        cls = gm.NODE_CLASSES[node_type]
        for prop in props:
            assert isinstance(getattr(cls, prop, None), property), (node_type, prop)
