"""gm.ui element trees — the machinery behind `with gm.ui.col():`.

Author-facing `gm.ui.*` calls live in ui.py: name inference only hops frames in
`pygeomatic.ui`. `ui_schema.json` is generated by the web repo's
`npm run gen:ui-schema`.
"""

from __future__ import annotations

import json
import re
from contextlib import contextmanager
from contextvars import ContextVar
from importlib.resources import files
from typing import Optional

from .store import IDENTIFIER_RE, Store, current_store


class UITreeError(ValueError):
    """A gm.ui element tree could not be built."""


_INTERPOLATION = re.compile(r"\$\{([a-zA-Z][a-zA-Z0-9-]*)\}")


# Open containers, innermost last.
_stack: ContextVar[Optional[list[dict]]] = ContextVar(
    "pygeomatic_uitree_stack", default=None
)


def _schema() -> dict:
    """The element vocabulary, loaded once from the generated JSON."""
    global _SCHEMA_CACHE
    if _SCHEMA_CACHE is None:
        text = (files("pygeomatic") / "ui_schema.json").read_text(encoding="utf-8")
        _SCHEMA_CACHE = json.loads(text)
    return _SCHEMA_CACHE


_SCHEMA_CACHE: Optional[dict] = None


def _real(mapping: dict) -> dict:
    """Drop the `_comment` keys the schema carries for its human readers."""
    return {k: v for k, v in mapping.items() if not k.startswith("_")}


def open_container() -> Optional[dict]:
    """The innermost open container element, or None when no tree is open."""
    stack = _stack.get()
    return stack[-1] if stack else None


def in_tree() -> bool:
    """Whether a `gm.ui` container is currently open."""
    return bool(_stack.get())


MAX_SPACE_STEP = 9


def _check_size(where: str, name: str, value):
    """A `size`: a spacing step, `"fill"`, or `<number><allowed unit>`."""
    units = _schema()["sizeUnits"]
    if isinstance(value, bool):
        raise UITreeError(f"{where}.{name} must be a length, got {value!r}")
    if isinstance(value, int):
        if not 0 <= value <= MAX_SPACE_STEP:
            raise UITreeError(
                f"{where}.{name} as a number must be a spacing step "
                f"between 0 and {MAX_SPACE_STEP}, got {value}"
            )
        return value
    if not isinstance(value, str):
        raise UITreeError(
            f"{where}.{name} must be a number, \"fill\", or a length like \"12ch\""
        )
    if value == "fill":
        return value
    for unit in units:
        if value.endswith(unit):
            head = value[: -len(unit)]
            try:
                float(head)
            except ValueError:
                break
            return value
    raise UITreeError(
        f"{where}.{name} must use one of {', '.join(units)} — got {value!r}"
    )


def _check_font_size(where: str, name: str, value):
    """A `fontsize`: a positive length in one of the font units."""
    units = _schema()["fontUnits"]
    if not isinstance(value, str):
        raise UITreeError(
            f'{where}.{name} must be a length like "0.9rem" or "14px", got {value!r}'
        )
    for unit in units:
        if value.endswith(unit):
            head = value[: -len(unit)]
            try:
                size = float(head)
            except ValueError:
                break
            if size <= 0:
                raise UITreeError(f"{where}.{name} must be positive, got {value!r}")
            return value
    raise UITreeError(
        f"{where}.{name} must use one of {', '.join(units)} — got {value!r}"
    )


def _check_attr(where: str, name: str, spec: dict, value):
    kind = spec["type"]

    if kind == "number":
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise UITreeError(f"{where}.{name} must be a number, got {value!r}")
        return float(value) if isinstance(value, float) else value

    if kind == "space":
        if isinstance(value, bool) or not isinstance(value, int):
            raise UITreeError(
                f"{where}.{name} must be a whole number of spacing steps, got {value!r}"
            )
        if not 0 <= value <= MAX_SPACE_STEP:
            raise UITreeError(
                f"{where}.{name} must be between 0 and {MAX_SPACE_STEP}, got {value}"
            )
        return value

    if kind == "size":
        return _check_size(where, name, value)

    if kind == "fontsize":
        return _check_font_size(where, name, value)

    if kind == "string":
        if not isinstance(value, str):
            raise UITreeError(f"{where}.{name} must be a string, got {value!r}")
        return value

    if kind == "identifier":
        if not isinstance(value, str) or not IDENTIFIER_RE.match(value):
            raise UITreeError(
                f"{where}.{name} must be an identifier (a letter, then letters, "
                f"digits or dashes), got {value!r}"
            )
        return value

    if kind == "bool":
        if not isinstance(value, bool):
            raise UITreeError(f"{where}.{name} must be True or False, got {value!r}")
        return value

    if kind == "enum":
        if value not in spec["values"]:
            raise UITreeError(
                f"{where}.{name} must be one of {', '.join(spec['values'])}, "
                f"got {value!r}"
            )
        return value

    if kind == "options":
        if isinstance(value, dict):
            node = value.get("node")
            if set(value) != {"node"} or not isinstance(node, str) or not IDENTIFIER_RE.match(node):
                raise UITreeError(f"{where}.{name} must be a non-empty list or {{'node': <identifier>}}")
            return {"node": node}
        if not isinstance(value, (list, tuple)) or not value:
            raise UITreeError(f"{where}.{name} must be a non-empty list")
        return list(value)

    if kind == "cond":
        if not isinstance(value, dict):
            raise UITreeError(f"{where}.{name} must be a condition")
        return value

    return value  # "any"


def build_element(tag: str, attrs: dict, sizing: dict) -> dict:
    """Validate one element's attributes and return it. `None` values are dropped."""
    schema = _schema()
    tags = _real(schema["tags"])
    if tag not in tags:
        raise UITreeError(f"{tag!r} is not a gm.ui element")
    spec = tags[tag]
    allowed = _real(spec["attrs"])

    element: dict = {"tag": tag}

    for name, value in sizing.items():
        if value is None:
            continue
        shared = _real(schema["sizing"])
        if name not in shared:
            raise UITreeError(f"{tag}.{name} is not a layout attribute")
        element[name] = _check_attr(tag, name, shared[name], value)

    for name, attr_spec in allowed.items():
        if name in attrs and (attrs[name] is not None or name == "initialValue"):
            element[name] = _check_attr(tag, name, attr_spec, attrs[name])
        elif attr_spec.get("required"):
            raise UITreeError(f"gm.ui.{tag} needs {name}")

    unknown = sorted(
        name for name, value in attrs.items() if value is not None and name not in allowed
    )
    if unknown:
        raise UITreeError(
            f"gm.ui.{tag} has no attribute{'s' if len(unknown) > 1 else ''}: "
            f"{', '.join(unknown)}"
        )
    return element


def add_element(element: dict) -> None:
    """Attach a finished element to the open container."""
    parent = open_container()
    if parent is None:
        raise UITreeError(
            f"gm.ui.{element['tag']} needs an open container — put it inside a "
            "`with gm.ui.col():` or `with gm.ui.row():` block"
        )
    parent.setdefault("children", []).append(element)


@contextmanager
def container(tag: str, attrs: dict, sizing: dict):
    """Open a container; on exit attach it to its parent, or emit it if outermost."""
    element = build_element(tag, attrs, sizing)
    element["children"] = []

    stack = _stack.get()
    outermost = not stack
    if outermost:
        stack = []
        token = _stack.set(stack)
    else:
        token = None
    stack.append(element)
    try:
        yield element
    finally:
        stack.pop()
        if token is not None:
            _stack.reset(token)

    if not element["children"]:
        raise UITreeError(f"gm.ui.{tag} block is empty, so it would render nothing")

    if outermost:
        _emit(element)
    else:
        add_element(element)


def _emit(root: dict) -> None:
    """Register a finished tree and write its placeholder into the article."""
    from .article import md_raw

    store = current_store()
    tree_id = f"t{len(store.ui_trees)}"
    store.ui_trees[tree_id] = root
    md_raw(f'<div class="nova-ui-tree" data-tree="{tree_id}"></div>')


def harvest_ui_trees(store: Optional[Store] = None) -> dict:
    """The session's element trees as `{tree id: root element}`."""
    store = store or current_store()
    return {tree_id: root for tree_id, root in store.ui_trees.items()}


def node_refs(element: dict, into: set) -> set:
    """Every store node id a tree reads, so the compiler can check they exist."""
    if "node" in element:
        into.add(element["node"])
    cond = element.get("cond")
    if isinstance(cond, dict):
        _cond_refs(cond, into)
    for name in ("text",):
        value = element.get(name)
        if isinstance(value, str):
            for ref in _INTERPOLATION.findall(value):
                into.add(ref)
    for child in element.get("children", ()):
        node_refs(child, into)
    return into


def _cond_refs(payload: dict, into: set) -> None:
    from .cond import node_refs as cond_node_refs

    cond_node_refs(payload, into)
