#!/usr/bin/env python3
"""Regenerate `src/pygeomatic/katex_commands.json` from a KaTeX bundle.

The committed JSON is a **self-contained copy** of KaTeX's command set — the
article math linter (`latex_lint.py`) loads only that file, never any external
path, so it can flag an undefined macro like `\\emerald` before the article
ships. This script is the dev-time tool that produced the copy; run it only to
refresh the copy after bumping KaTeX.

Every command name in KaTeX (symbols, functions, macros, and the commands they
expand to) is stored as a JS string literal `"\\name"`. We read the readable ESM
bundle and extract every `\\name` token — a superset that is safe for a linter:
missing a name would only cause a false *positive*, and including an internal
one only a false *negative* (both rare, the latter harmless).

KaTeX is a public npm package; install it in THIS repo to regenerate:
    npm install --no-save katex
    uv run python scripts/gen_katex_commands.py

Or point at any katex.mjs explicitly:
    uv run python scripts/gen_katex_commands.py path/to/katex/dist/katex.mjs
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
# Standard npm layout inside THIS repo (from `npm install katex`). No external
# repo is assumed; pass an explicit path to use a katex install elsewhere.
_DEFAULT_KATEX = _REPO / "node_modules/katex/dist/katex.mjs"
_OUT = _REPO / "src/pygeomatic/katex_commands.json"

# A double-backslash source escape (`"\\alpha"`) followed by a letter run.
_NAME_RE = re.compile(r"\\\\([a-zA-Z]+)")


def extract(bundle: str) -> list[str]:
    names = {m.group(1) for m in _NAME_RE.finditer(bundle)}
    return sorted(names)


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else _DEFAULT_KATEX
    if not src.exists():
        print(
            f"KaTeX bundle not found: {src}\n"
            "Install the public package here (`npm install --no-save katex`) or "
            "pass a path to katex.mjs as the first argument.",
            file=sys.stderr,
        )
        return 1
    names = extract(src.read_text(encoding="utf-8"))
    version = _katex_version(src)
    payload = {
        "_source": f"katex {version} ({src.name})",
        "_note": "Generated by scripts/gen_katex_commands.py — do not edit by hand.",
        "commands": names,
    }
    _OUT.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {len(names)} commands from katex {version} -> {_OUT.relative_to(_REPO)}")
    return 0


def _katex_version(bundle: Path) -> str:
    pkg = bundle.parent.parent / "package.json"
    try:
        return json.loads(pkg.read_text())["version"]
    except Exception:
        return "unknown"


if __name__ == "__main__":
    raise SystemExit(main())
